### PR TITLE
add mistral + chatml prompts

### PR DESCRIPTION
**Pull request by cognitivetech**
this adds what I believe is the correct prompt formatting for Mistral.. based on testing where I've rated it best vs llama-index and llama2

### CODE REVIEW

**Review by louis-jaris — COMMENTED** [review]
Tests are missing -- they will help maintainers to review the difference between `llama2` and `mistral` prompt format.

**Comment by cognitivetech** [comment]
> Tests are missing -- they will help maintainers to review the difference between `llama2` and `mistral` prompt format.

i've added a test... which is failing, because it doesn't take into account my system prompt... which... 

I believe highlights the point that those other prompts aren't actually using the system prompt... just not sure what to do now.

**Comment by cognitivetech** [comment]
I removed `def test_mistral_prompt_style_with_system_prompt():` because there aren't two expected behaviors. a given prompt method should _always_ add the system prompt.

However, I am not doing anything else until one of the more experienced maintainers can review my code \ thought process.

Maybe I'm missing something entirely

**Comment by cognitivetech** [comment]
IDK what ruff wants of me.. I tired --fix and it didn't like the result, so I added space between the external vs internal imports, like in the original, still fail.

I'm a newb to python testing, but.. I will admit the test helped me fix some problems.

what with ruff, idk.

**Comment by cognitivetech** [comment]
ok, all checks passed :sweat_smile:

**Comment by cognitivetech** [comment]
ok, now I'm seeing the discussion where system prompt is only set for Gradio users https://github.com/imartinez/privateGPT/pull/1353

annnd, now I see in the api documentation where I can set system prompt as part of my api call :face_exhaling: 

okok... now I'm getting closer :sweat_smile: but .... at least I understand my confusion from before.

**Review by imartinez — APPROVED** [review]
Amazing 😍

**Pull request merged**
