### PR TITLE
Add support for Ollama LLM

### PR DESCRIPTION
**Pull request by ygalblum**
Allow using Ollama as the LLM

### CODE REVIEW

**Comment by Fau57** [comment]
AGREED!

**Comment by oatmealm** [comment]
I'm trying this branch ... its seems to to want to build lllamacpp...

settings-ollama.yaml

``` 
ollama:
  model: llama2:latest
```

```
PGPT_PROFILES=ollama make run
```

```
  File "/home/user/src/privateGPT/private_gpt/components/llm/llm_component.py", line 38, in __init__
    self.llm = LlamaCPP(
               ^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/private-gpt-o6kY6e_Z-py3.11/lib/python3.11/site-packages/llama_index/llms/llama_cpp.py", line 119, in __init__
    raise ValueError(
ValueError: Provided model path does not exist. Please check the path or provide a model_url to download.
```

**Comment by ygalblum** [comment]
@oatmealm you also need to set the llm mode:
```
llm:
  mode: ollama
```

**Review by imartinez — CHANGES_REQUESTED** [review]
Amazing! Could you update the documentation so people can figure out how to use this? 

https://docs.privategpt.dev/manual/advanced-setup/llm-backends

Just update the markdown in fern/docs/pages/manual/llms.mdx

**Comment by ygalblum** [comment]
> Could you update the documentation so people can figure out how to use this?

Done

**Review by imartinez — APPROVED** [review]

**Comment by icsy7867** [comment]
This is great! Ollama now supports the openai api format. I have just been running privategpt using the "openailike" which has been working fine.

**Comment by skywalker123p** [comment]
How can I combine embeddings when using Ollama LLM? Please give example of configuration and how to run it? thanks

**Pull request merged**
