### PR TITLE
bump pymupdf to 1.23.3 so it runs on M1/M2 macs

### PR DESCRIPTION
**Pull request by cheapsteak**
otherwise getting 

```
Creating new vectorstore
Loading documents from source_documents
Loading new documents:   0%|                              | 0/1 [00:02<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/pdf.py", line 297, in __init__
    import fitz  # noqa:F401
    ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fitz/__init__.py", line 22, in <module>
    from fitz.fitz import *
  File "/opt/homebrew/lib/python3.11/site-packages/fitz/fitz.py", line 14, in <module>
    from . import _fitz
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/fitz/_fitz.so, 0x0002): tried: '/opt/homebrew/lib/python3.11/site-packages/fitz/_fitz.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.11/site-packages/fitz/_fitz.so' (no such file), '/opt/homebrew/lib/python3.11/site-packages/fitz/_fitz.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

### CODE REVIEW

**Comment by paulinetheitgirl** [comment]
This fixed the `ImportError: 'PyMuPDF' package not found` I was getting. Thanks!

**Review by Duckybee — APPROVED** [review]
the latest one is 1.23.4 and it works for me as well

**Review by Duckybee — CHANGES_REQUESTED** [review]
You may also want to update in the pyproject.toml file and the lock as well

**Comment by cheapsteak** [comment]
oh yup, thanks

**Review by Duckybee — APPROVED** [review]

**Comment by cheapsteak** [comment]
Looks like project was restructured to no longer have these files

**Pull request closed without merging**
