### PR TITLE
Add support for Azure OpenAI

### PR DESCRIPTION
**Pull request by olederle**
Allows to use Azure OpenAI as LLM and embedding model.

### CODE REVIEW

**Review by imartinez — APPROVED** [review]
Great addition! As an optional idea, I'd suggest to include this option in the installation docs, both in the list of available options to select and as a recommended setup. https://docs.privategpt.dev/installation/getting-started/installation

**Comment by imartinez** [comment]
@olederle please run `make check` and `make test` locally. Apparently there are some issues with `make check` that are preventing the merge.

**Comment by SeifBach** [comment]
hey guys just a heads up in the doc [fern/docs/pages/manual/llms.mdx] you guys wrote
api_version: <api_version> # The API version to use. Default is "2023_05_15"
when i tried it it gave me a 404 but worked with dashes instead of underscores 2023-05-15

**Comment by olederle** [comment]
> hey guys just a heads up in the doc [fern/docs/pages/manual/llms.mdx] you guys wrote api_version: <api_version> # The API version to use. Default is "2023_05_15" when i tried it it gave me a 404 but worked with dashes instead of underscores 2023-05-15

That is right. For my use case I have used a preview api_version but want to have a stable version as default. But I introduced a typo with this. This is fixed now.

**Comment by olederle** [comment]
> @olederle please run `make check` and `make test` locally. Apparently there are some issues with `make check` that are preventing the merge.

@imartinez This should be fixed now and I have also updated the docs.

**Review by imartinez — APPROVED** [review]

**Pull request merged**
