### PR TITLE
Update requirements.txt to refer to pypandoc

### PR DESCRIPTION
**Pull request by soda3x**

### CODE REVIEW

**Comment by soda3x** [comment]
This should solve #226

**Review by GeeksikhSecurity — APPROVED** [review]
Tested and resolves the error https://github.com/imartinez/privateGPT/issues/226

**Comment by chenzilu1990** [comment]
Tested and resolves the error https://github.com/imartinez/privateGPT/issues/226

**Comment by azigler** [comment]
Also resolves #226 for me.

**Comment by imartinez** [comment]
We already merged #240 which contained the same chage. Thanks a lot!

**Pull request closed without merging**
