### PR TITLE
Updated ui.py to include a small sleep timer

### PR DESCRIPTION
**Pull request by icsy7867**
…m deltas.  This recursive function fires off so quickly to eats up too much of the CPU.  This small sleep frees up the CPU to not be bottlenecked.  This value can go lower/shorter.  But 0.02 or 0.025 seems to work well.

**Here you can view the slow down before the modifications (sorry for the poor quality):**

Screen Recording - End

**And here you can view the speed up after:**
Screen Recording 2024-02-07 at 6 30 29 PM

The entire process before this small change, the chat stream took 60-120 seconds or so.
**However after the change it takes about 8-10 seconds for me.**

### CODE REVIEW

**Review by EEmlan — APPROVED** [review]
Have tested this.
Now the Generation in the UI runs significantly faster

**Comment by ic-mw** [comment]
Excellent, it works nicely. I can confirm that the text output speed increases dramatically, about 10x. Good catch! 👍

**Comment by lolo9538** [comment]
Thank you SO MUCH!!!!!

**Comment by lolo9538** [comment]
Hi, I wonder if there is a similar issue for the ingest part. I have several thousands of documents to ingest and I see the GPU is not used at all and the CPU is barely used. I have upped the settings to 
embedding:
  mode: mock
  ingest_mode: parallel
  count_workers: 8

But the ingest is still very slow. Can anyone confirm whether ingest should be done by the GPU?
Thanks

**Review by imartinez — APPROVED** [review]

**Pull request merged**
