### PR TITLE
Add Poetry

### PR DESCRIPTION
**Pull request by morsamatias**
Hi! I have added support for [poetry](https://python-poetry.org) to manage the dependencies in a better way. 
I didn't remove the requirements.txt file so it has **backward compatibility.** 

Added:
- [x] pyproyect.toml
- [x] poetry.lock

Modified:
- [x] README.md

Note: The pyproyect has the dependencies updated but the requirements doesn't. I did it to keep the **backward compatibility.**  

**I add** the poetry installation in the README.md

### CODE REVIEW

**Comment by morsamatias** [comment]
@imartinez

**Comment by imartinez** [comment]
@morsamatias I'd be great if you could add the readme instructions as an alternative way to install the dependencies. Thanks!!

**Comment by morsamatias** [comment]
> @morsamatias I'd be great if you could add the readme instructions as an alternative way to install the dependencies. Thanks!!

Done!

**Comment by morsamatias** [comment]
@imartinez I have test it with the new ones in the poetry file and they work ok. I didn't update the one in the requirements.txt to keep the backward compatibility. If you want I can open a new PR with updating also that dependencies.

**Review by imartinez — APPROVED** [review]

**Comment by imartinez** [comment]
That'd be awesome, thanks @morsamatias !

**Comment by imartinez** [comment]
I just did it myself. Thanks @morsamatias

**Pull request merged**
