### PR TITLE
Feature/sentence transformers embeddings

### LINKED ISSUE #10: Suggestions for speeding up ingestion?
I presume I must be doing something wrong, as it is taking hours to ingest a 500kbyte text on an i9-12900 with 128GB.  In fact it's not even done yet.  Using models are recommended.

Help?

Thanks

Some output:

llama_print_timings:        load time =   674.34 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time = 12526.78 ms /   152 tokens (   82.41 ms per token)
llama_print_timings:        eval time =   157.46 ms /     1 runs   (  157.46 ms per run)
llama_print_timings:       total time = 12715.48 ms

### LINKED ISSUE #220: LLaMa model no longer supported
I'm trying to ingest the state of the union text, without having modified anything other than downloading the files/requirements and the .bin files.

It's giving me this error:

```
/usr/local/bin/python3 /Users/magnusmabeck/privateGPT/ingest.py
%                                                                                                                                                          
magnus@MBA---Magnus privateGPT % /usr/local/bin/python3 /Users/magnus/privateGPT/ingest.py
Loading documents from source_documents
Loaded 1 documents from source_documents
Split into 90 chunks of text (max. 500 tokens each)
llama.cpp: loading model from /Users/magnusmabeck/privateGPT/models/ggml-model-q4_0.bin
llama.cpp: can't use mmap because tensors are not aligned; convert to new format to avoid this
llama_model_load_internal: format     = 'ggml' (old version with low tokenizer quality and no mmap support)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1024
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
error loading model: this format is no longer supported (see https://github.com/ggerganov/llama.cpp/pull/1305)
llama_init_from_file: failed to load model
```

It seems the creator of llama.ccp (https://github.com/ggerganov/llama.cpp) has changed the bit-order which breaks former quantizations. 

Is no one else having this "bug" or does anyone have some updated quantizationed models?

**Environment (please complete the following information):**
 - OS / hardware: [macOS 13.3 / M2]
 - Python version [3.11.3]

### PR DESCRIPTION
**Pull request by imartinez**
After testing different models, I suggest to stop using llama.cpp as an embeddings model and switch to [Sentence-Transformers](https://www.sbert.net/).

From my initial tests with this new approach I obtained:
- better results in terms of the similarity semantic search used to include in the LLM prompt, improving the overall result of the tool (embeddings + LLM)
- way faster ingest: 10 seconds to ingest a 60-pages PDF on a Mac M1 (fixes #10 , #166, #152)
- avoids the recent issues with llama.cpp (fixes #220, #15, #213)

That's why I propose to make this change to the main branch.

Note: this is a breaking change. Existing local vector databases won't work with the new embeddings model. Those that want to keep the current database should not update to this commit.

### CODE REVIEW

**Comment by imartinez** [comment]
@andreakiro @alxspiker @R-Y-M-R @sorin @katojunichi893 Could you take a look, test it, and let me know what you think? Thanks in advance!

**Review by andreakiro — APPROVED** [review]
LGTM for the PR 🦙 I'd be cool adding a `./scripts/setup` that download models beforehand and setups the working environment for users. This would need internet connection, but once executed, the project could be used 100% offline (without having to run `ingest` online once).

**Comment by imartinez** [comment]
> LGTM for the PR 🦙 I'd be cool adding a `./scripts/setup` that download models beforehand and setups the working environment for users. This would need internet connection, but once executed, the project could be used 100% offline (without having to run `ingest` online once).

I think that's a very good idea! Maybe we can leave it for a next PR though, to keep things separate.

**Comment by pseudotensor** [comment]
Ya, it's known that using LLM model decoder-based embeddings makes little sense for vector search.  For h2ogpt we use the standard "best" `sentence-transformers/all-MiniLM-L6-v2` HF model.  But one should also consider instruct-xl.

See:  https://github.com/h2oai/h2ogpt

**Comment by andreakiro** [comment]
@pseudotensor Agree that `instruct-xl` could also be interesting. Best option would be to extend codebase to be able to handle all of these models, depending on selected user choice in `.env` file. This should not be too much work neither.

**Comment by imartinez** [comment]
Thanks for your comments. I'll merge this change right away so the community can benefit from a lot faster ingestion times and better context injection in the prompt, and we can make it more flexible to accommodate different embeddings models later on.

**Comment by lhumeau** [comment]
> After testing different models, I suggest to stop using llama.cpp as an embeddings model and switch to [Sentence-Transformers](https://www.sbert.net/).
> 
> From my initial tests with this new approach I obtained:
> 
> * better results in terms of the similarity semantic search used to include in the LLM prompt, improving the overall result of the tool (embeddings + LLM)
> * way faster ingest: 10 seconds to ingest a 60-pages PDF on a Mac M1 (fixes [Suggestions for speeding up ingestion? #10](https://github.com/imartinez/privateGPT/issues/10) , [Ingest going on forever #166](https://github.com/imartinez/privateGPT/issues/166), [How to make the ingesting faster? #152](https://github.com/imartinez/privateGPT/issues/152))
> * avoids the recent issues with llama.cpp (fixes [LLaMa model no longer supported #220](https://github.com/imartinez/privateGPT/issues/220), [llama.cpp: can't use mmap because tensors are not aligned; convert to new format to avoid this #15](https://github.com/imartinez/privateGPT/issues/15), [Version mismatch with llama.cpp model? #213](https://github.com/imartinez/privateGPT/issues/213))
> 
> That's why I propose to make this change to the main branch.
> 
> Note: this is a breaking change. Existing local vector databases won't work with the new embeddings model. Those that want to keep the current database should not update to this commit.

Double check this project it have GPU..
https://github.com/lm-sys/FastChat

**Pull request merged**
