### PR TITLE
Delete all files button

### PR DESCRIPTION
**Pull request by Robinsane**
Button to delete all ingested files. (+ ability to disable the button in settings.yaml)

When first using pgpt I could've used this myself (now I use Python SDK)
I saw multiple cases where people wanted something similar (issues / Discord).

issue example:
https://github.com/imartinez/privateGPT/issues/1559

### CODE REVIEW

**Comment by Robinsane** [comment]
Will look into expanding this PR /w button to delete just 1 file

**Comment by Robinsane** [comment]
Added code with a button to delete a single file

Not happy yet with this:
- multiple users deleting single file at the same time => problem : only last selected file will be deleted (will not happen often & you can disable button in settings.yaml)
- I'd like to refresh the list of ingested files somehow but can't seem to figure out how

**Review by TobiasJu — COMMENTED** [review]
Cloned the repo, ran the code. 
Thanks for your work!
Found one minor issue. The "Delete all files" button is permanently disabled.

image

**Comment by Robinsane** [comment]
@TobiasJu 
This was intentional
See settings.yaml

`  delete_file_button_enabled: true
  delete_all_files_button_enabled: false`
  
  If most of you agree I'll make both true by default
  I was thinking for multiple users you don't want an accidental click to go poof (other button doesn't do anything unless a file is selected)

**Comment by imartinez** [comment]
Included in https://github.com/imartinez/privateGPT/pull/1612

(btw, I made both buttons visible by default)

**Pull request closed without merging**
