### PR TITLE
Created auto closes old / inactive issues Workflow

### PR DESCRIPTION
**Pull request by Killer2OP**

### CODE REVIEW

**Comment by pabloogc** [comment]
I don't think this auto comments give much value. However, if you want to repurpose the PR to add the bot that auto closes old / inactive issues that I would be happy to include in the project.

**Comment by Killer2OP** [comment]
> I don't think this auto comments give much value. However, if you want to repurpose the PR to add the bot that auto closes old / inactive issues that I would be happy to include in the project.

Yes, I can do that .
What should be the time period means how much days for a issue to be opened?

**Comment by Killer2OP** [comment]
@pabloogc Review the PR.

**Comment by pabloogc** [comment]
I don't like the idea of using a bash script, it offers very little customization and it's hard to read.

I will close this PR for now, if you want to contribute look at other OS repositories and try to follow good practices, for example using [actions/stale](https://github.com/marketplace/actions/close-stale-issues)

**Pull request closed without merging**
