### PR TITLE
added sentence_transformers to requirements

### PR DESCRIPTION
**Pull request by Deventual**
add

### CODE REVIEW

**Review by Daethyra — APPROVED** [review]
Noticed the missing packaged when trying to install tonight
- I approve this commit

**Review by Daethyra — CHANGES_REQUESTED** [review]
- Recommend updating `pyproject.toml`
   - sentence_transformers = "^2.2.2"

**Review by kpbird — APPROVED** [review]

**Review by Simon-XG-Yan — APPROVED** [review]

**Review by Daethyra — APPROVED** [review]

**Review by tjcaul — APPROVED** [review]
The dependency of `sentence_transformers` was not met after running `pip install -r requirements.txt`. Adding it to `requirements.txt` fixes it and makes it easier to install privateGPT.

**Comment by imartinez** [comment]
Thanks! Done in https://github.com/imartinez/privateGPT/pull/960

**Pull request closed without merging**
